const KEYS={members:'scorekeeper_members',rounds:'scorekeeper_rounds',ended:'scorekeeper_ended',max:'scorekeeper_max',history:'scorekeeper_history',gameId:'scorekeeper_db_game_id'};
const $=id=>document.getElementById(id);
const els={authPanel:$('authPanel'),authForm:$('authForm'),authEmail:$('authEmail'),authPassword:$('authPassword'),authTitle:$('authTitle'),authSubtitle:$('authSubtitle'),authSubmit:$('authSubmit'),authToggle:$('authToggle'),authNotice:$('authNotice'),appShell:$('appShell'),signOut:$('signOutBtn'),addForm:$('addForm'),nameInput:$('nameInput'),membersList:$('membersList'),endGameBtn:$('endGameBtn'),resetBtn:$('resetBtn'),winner:$('winner'),start:$('startGameBtn'),roundInfo:$('roundInfo'),roundTitle:$('roundTitle'),roundForm:$('roundForm'),roundInputs:$('roundInputs'),submitRound:$('submitRoundBtn'),roundsHistory:$('roundsHistory'),memberCount:$('memberCount'),createSlots:$('createSlotsBtn'),bulkForm:$('bulkAddForm'),slots:$('memberSlots'),cancelSlots:$('cancelSlotsBtn'),saveMembers:$('saveMembersBtn'),max:$('maxScoreInput'),undo:$('undoRoundBtn'),confirmModal:$('confirmModal'),confirmMessage:$('confirmMessage'),confirmYes:$('confirmYes'),confirmNo:$('confirmNo'),db:$('dbStatus'),historyBtn:$('historyBtn'),historyModal:$('historyModal'),historyList:$('historyList'),historyClose:$('historyClose'),historyCloseTop:$('historyCloseTop'),historyRefresh:$('historyRefresh'),newGame:$('newGameBtn'),saveGameBtn:$('saveGameBtn'),prev:$('historyPrev'),next:$('historyNext'),pageInfo:$('historyPageInfo'),countBadge:$('playerCountBadge'),notice:$('gameNotice'),scoreboard:$('scoreBoard')};
let members=readJSON(KEYS.members,[]).map(normalizeMember),rounds=readJSON(KEYS.rounds,[]).map(normalizeRound),ended=localStorage.getItem(KEYS.ended)==='true',inGame=false,maxScore=Number(localStorage.getItem(KEYS.max)||0),DB_GAME_ID=localStorage.getItem(KEYS.gameId)||null,supabaseClient=null,currentHistoryPage=1,historyTotalCount=0,confirmAction=null;
let roundNumber=rounds.length+1,currentUser=null,authRegisterMode=false;
try{if(typeof SUPABASE_URL!=='undefined'&&typeof SUPABASE_ANON_KEY!=='undefined'&&window.supabase)supabaseClient=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY)}catch(e){console.warn(e)}
function readJSON(k,f){try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}}
function normalizeMember(m){return {name:String(m?.name||'').trim(),score:Number(m?.score??m?.total??0)||0,eliminated:Boolean(m?.eliminated),db_id:m?.db_id||null}}
function normalizeRound(r){return Array.isArray(r)?r.map(v=>Number(v)||0):[]}
function persist(){localStorage.setItem(KEYS.members,JSON.stringify(members));localStorage.setItem(KEYS.rounds,JSON.stringify(rounds));localStorage.setItem(KEYS.ended,String(ended));localStorage.setItem(KEYS.max,String(maxScore||0));if(DB_GAME_ID)localStorage.setItem(KEYS.gameId,DB_GAME_ID);else localStorage.removeItem(KEYS.gameId)}
function setNotice(msg,type='info'){els.notice.textContent=msg||'';els.notice.dataset.type=type}
function setAuthNotice(msg,type='info'){els.authNotice.textContent=msg||'';els.authNotice.dataset.type=type}
function updateAuthMode(){els.authTitle.textContent=authRegisterMode?'Create your account':'Welcome back';els.authSubtitle.textContent=authRegisterMode?'Register with email and password to save your games.':'Sign in to save and access your games.';els.authSubmit.textContent=authRegisterMode?'Register':'Sign In';els.authToggle.textContent=authRegisterMode?'Already have an account? Sign in':'Need an account? Register'}
async function authenticate(e){e.preventDefault();if(!supabaseClient){setAuthNotice('Supabase is not configured. Local mode is available below.','error');return}const email=els.authEmail.value.trim(),password=els.authPassword.value;const result=authRegisterMode?await supabaseClient.auth.signUp({email,password}):await supabaseClient.auth.signInWithPassword({email,password});if(result.error){setAuthNotice(result.error.message,'error');return}if(authRegisterMode&&!result.data.session)setAuthNotice('Registration successful. Check your email to confirm your account.','success');else setAuthNotice('Signed in successfully.','success')}
function handleAuthSession(session){currentUser=session?.user||null;const authenticated=Boolean(currentUser)||!supabaseClient;els.authPanel.hidden=authenticated;els.appShell.hidden=!authenticated;els.signOut.hidden=!currentUser;if(authenticated){render();if(currentUser)setTimeout(checkDB,0)}}
async function signOut(){if(supabaseClient)await supabaseClient.auth.signOut()}
function showConfirm(message,action){els.confirmMessage.textContent=message;confirmAction=action;els.confirmModal.hidden=false}
function closeConfirm(){els.confirmModal.hidden=true;confirmAction=null}
function escapeText(s){return String(s??'')}
function gameFinished(){return members.length>0&&members.some(m=>m.score>=maxScore&&maxScore>0)}
function getWinners(){if(!members.length)return[];const active=members.filter(m=>!m.eliminated);const pool=active.length?active:members;const min=Math.min(...pool.map(m=>m.score));return pool.filter(m=>m.score===min)}
function render(){
  els.countBadge.textContent=`${members.length} player${members.length===1?'':'s'}`;
  els.membersList.innerHTML='';
  if(!members.length){els.membersList.innerHTML='<div class="empty-state">No players yet. Add players to start a game.</div>'}
  members.forEach((m,i)=>{const card=document.createElement('div');card.className='player-card'+(m.eliminated?' eliminated':'');
    const info=document.createElement('div');const n=document.createElement('div');n.className='player-name';n.textContent=m.name;const meta=document.createElement('div');meta.className='player-meta';meta.textContent=m.eliminated?'Eliminated':'Active';info.append(n,meta);
    const total=document.createElement('div');total.className='player-total';total.textContent=m.score;
    const remove=document.createElement('button');remove.className='remove-player';remove.textContent='Remove';remove.disabled=inGame||ended;remove.onclick=()=>removeMember(i);
    card.append(info,total,remove);els.membersList.appendChild(card);
  });
  const winners=ended?getWinners():[];els.membersList.querySelectorAll('.player-card').forEach((c,i)=>{if(winners.some(w=>w===members[i]))c.classList.add('winner')});
  updateStartButton();
  els.roundForm.hidden=!inGame||ended;els.roundInfo.textContent=inGame?`Round ${roundNumber}`:ended?'Game ended':'Not started';els.roundTitle.textContent=`Round ${roundNumber}`;
  els.max.disabled=inGame||ended;els.max.value=maxScore||'';
  els.undo.hidden=rounds.length===0;els.undo.disabled=rounds.length===0||ended;
  els.endGameBtn.disabled=!inGame||ended;els.saveGameBtn.disabled=members.length===0;els.newGame.disabled=false;
  if(ended){els.winner.hidden=false;const ws=getWinners();els.winner.textContent=ws.length===1?`Winner: ${ws[0].name} (${ws[0].score})`:`Winners: ${ws.map(w=>w.name).join(', ')} (${ws[0]?.score??0})`}else els.winner.hidden=true;
  renderRoundInputs();renderScoreboard();renderRoundsHistory();
}
function validMax(){return Number.isInteger(maxScore)&&maxScore>0}
function updateStartButton(){if(!els.start)return;els.start.disabled=inGame||ended||members.length<2||!validMax();els.start.textContent=rounds.length?'Resume Game':'Start Game'}
function renderRoundInputs(){els.roundInputs.innerHTML='';if(!inGame)return;members.forEach((m,i)=>{const row=document.createElement('div');row.className='round-row';const label=document.createElement('label');label.htmlFor=`round-score-${i}`;label.textContent=m.name;const hint=document.createElement('span');hint.className='current-total';hint.textContent=`Total: ${m.score}`;label.appendChild(hint);const input=document.createElement('input');input.id=`round-score-${i}`;input.type='number';input.min='0';input.step='1';input.inputMode='numeric';input.placeholder='Score for this round';input.required=true;input.dataset.index=i;row.append(label,input);els.roundInputs.appendChild(row)})}
function renderScoreboard(){els.scoreboard.innerHTML='';if(!members.length)return;const sorted=members.map((m,i)=>({...m,index:i})).sort((a,b)=>a.score-b.score);sorted.forEach((m,rank)=>{const row=document.createElement('div');row.className='score-row'+(m.eliminated?' eliminated':'');const left=document.createElement('div');left.innerHTML=`<div class="player-name">${escapeText(m.name)}</div><div class="rank">Rank ${rank+1}</div>`;const score=document.createElement('div');score.className='score-value';score.textContent=m.score;const status=document.createElement('div');status.className='status';status.textContent=m.eliminated?'Eliminated':m.score>=maxScore&&maxScore?'At limit':'Active';row.append(left,score,status);els.scoreboard.appendChild(row)})}
function renderRoundsHistory(){if(!rounds.length){els.roundsHistory.innerHTML='<div class="empty-state">No rounds submitted yet.</div>';return}const table=document.createElement('table');table.className='rounds-table';const thead=document.createElement('thead'),hr=document.createElement('tr');['Round',...members.map(m=>m.name),'Total'].forEach(t=>{const th=document.createElement('th');th.textContent=t;hr.appendChild(th)});thead.appendChild(hr);table.appendChild(thead);const body=document.createElement('tbody');rounds.forEach((r,ri)=>{const tr=document.createElement('tr');const rd=document.createElement('td');rd.textContent=`R${ri+1}`;tr.appendChild(rd);members.forEach((m,i)=>{const td=document.createElement('td');td.textContent=r[i]??0;tr.appendChild(td)});const total=document.createElement('td');total.textContent=r.reduce((a,b)=>a+(Number(b)||0),0);tr.appendChild(total);body.appendChild(tr)});table.appendChild(body);els.roundsHistory.innerHTML='';els.roundsHistory.appendChild(table)}
function addMember(name){name=name.trim();if(!name)return;if(members.some(m=>m.name.toLowerCase()===name.toLowerCase())){setNotice('Player names must be unique.','error');return}members.push(normalizeMember({name}));persist();render();els.nameInput.value='';els.nameInput.focus()}
function removeMember(i){if(inGame||ended)return;showConfirm(`Remove ${members[i].name}?`,()=>{members.splice(i,1);persist();render()})}
function createSlots(){const n=Number(els.memberCount.value)||2;els.slots.innerHTML='';for(let i=0;i<n;i++){const input=document.createElement('input');input.id=`slot-${i}`;input.placeholder=`Player ${i+1} name`;input.required=true;input.maxLength=40;els.slots.appendChild(input)}els.bulkForm.hidden=false}
function cancelSlots(){els.bulkForm.hidden=true;els.slots.innerHTML=''}
function saveBulk(e){e.preventDefault();const names=[...els.slots.querySelectorAll('input')].map(x=>x.value.trim());if(names.some(n=>!n)||new Set(names.map(n=>n.toLowerCase())).size!==names.length){setNotice('Enter a unique name in every slot.','error');return}members=names.map(name=>normalizeMember({name}));rounds=[];ended=false;inGame=false;roundNumber=1;DB_GAME_ID=null;persist();cancelSlots();render();setNotice('Players created. Set a maximum score and start the game.','success')}
function startGame(){if(members.length<2){setNotice('Add at least 2 players before starting.','error');return}maxScore=Number(els.max.value);if(!validMax()){setNotice('Enter a valid maximum score greater than 0.','error');return}ended=false;inGame=true;roundNumber=rounds.length+1;members.forEach(m=>{m.eliminated=false});persist();render();setNotice(`Game started. Enter scores for Round ${roundNumber}.`,'success')}
function submitRound(e){e.preventDefault();if(!inGame||ended)return;const inputs=[...els.roundInputs.querySelectorAll('input')];const scores=inputs.map(i=>Number(i.value));if(scores.some(v=>!Number.isInteger(v)||v<0)){setNotice('Each round score must be a whole number 0 or greater.','error');return}const previous=members.map(m=>m.score);rounds.push(scores);members.forEach((m,i)=>{m.score=previous[i]+scores[i];if(m.score>=maxScore)m.eliminated=true});roundNumber++;persist();render();setNotice('Round submitted successfully.','success');if(gameFinished()){endGame(false)}}
function undoRound(){if(!rounds.length||ended)return;showConfirm(`Undo Round ${rounds.length}?`,()=>{const last=rounds.pop();members.forEach((m,i)=>{m.score=Math.max(0,m.score-(Number(last[i])||0));m.eliminated=false});roundNumber=rounds.length+1;persist();render();setNotice('Last round was undone.','success')})}
async function endGame(confirmIt=true){if(!members.length)return;const finish=async()=>{inGame=false;ended=true;members.forEach(m=>m.eliminated=m.score>=maxScore);persist();render();setNotice('Game ended. Save it to history if it is not already saved.','success');await saveGame(true)};if(confirmIt)showConfirm('End the current game? You can still save it to history afterward.',finish);else await finish()}
function resetGame(){showConfirm('Reset the current game completely? This removes players, rounds and the current saved-game link.',()=>{members=[];rounds=[];ended=false;inGame=false;maxScore=0;roundNumber=1;DB_GAME_ID=null;persist();render();setNotice('Game reset. Add players to begin a new game.','success')})}
function newGame(){if(members.length||rounds.length){showConfirm('Start a new game? Unsaved current progress will be cleared.',()=>{members=[];rounds=[];ended=false;inGame=false;maxScore=0;roundNumber=1;DB_GAME_ID=null;persist();render();setNotice('New game ready.','success')})}else{render()}}
async function createDBGame(){if(!supabaseClient)return null;const {data,error}=await supabaseClient.from('games').insert({name:`Game ${new Date().toISOString()}`,max_score:maxScore,ended,user_id:currentUser.id}).select('id,name,max_score,ended,created_at').single();if(error)throw error;DB_GAME_ID=data.id;const mrows=members.map(m=>({game_id:data.id,name:m.name,total:m.score,eliminated:m.eliminated}));const {data:md,error:me}=await supabaseClient.from('members').insert(mrows).select('id,name,total,eliminated');if(me)throw me;members.forEach((m,i)=>m.db_id=md[i]?.id||null);if(rounds.length){const rr=rounds.map((scores,i)=>({game_id:data.id,round_number:i+1,scores}));const {error:re}=await supabaseClient.from('rounds').insert(rr);if(re)throw re}persist();return data}
async function updateDBGame(){if(!supabaseClient||!DB_GAME_ID)return null;const {error}=await supabaseClient.from('games').update({max_score:maxScore,ended}).eq('id',DB_GAME_ID);if(error)throw error;const {error:me}=await supabaseClient.from('members').delete().eq('game_id',DB_GAME_ID);if(me)throw me;const mrows=members.map(m=>({game_id:DB_GAME_ID,name:m.name,total:m.score,eliminated:m.eliminated}));const {data:md,error:mi}=await supabaseClient.from('members').insert(mrows).select('id,name,total,eliminated');if(mi)throw mi;members.forEach((m,i)=>m.db_id=md[i]?.id||null);const {error:re}=await supabaseClient.from('rounds').delete().eq('game_id',DB_GAME_ID);if(re)throw re;if(rounds.length){const rr=rounds.map((scores,i)=>({game_id:DB_GAME_ID,round_number:i+1,scores}));const {error:ri}=await supabaseClient.from('rounds').insert(rr);if(ri)throw ri}persist();return true}
function localHistory(){return readJSON(KEYS.history,[])}
function saveLocalHistory(){if(!ended)return;const h=localHistory();const record={id:DB_GAME_ID||`local-${Date.now()}`,name:`Game ${new Date().toISOString()}`,created_at:new Date().toISOString(),max_score:maxScore,members:members.map(m=>({name:m.name,total:m.score,eliminated:m.eliminated})),rounds:rounds.map((scores,i)=>({round_number:i+1,scores})),winner:getWinners().map(w=>w.name)};const idx=h.findIndex(x=>x.id===record.id);if(idx>=0)h[idx]=record;else h.unshift(record);localStorage.setItem(KEYS.history,JSON.stringify(h.slice(0,200)))}
async function saveGame(silent=false){if(!members.length){setNotice('Add players before saving.','error');return false}try{if(supabaseClient){if(DB_GAME_ID)await updateDBGame();else await createDBGame();els.db.textContent='DB: saved'}else{saveLocalHistory();els.db.textContent='DB: local backup'}saveLocalHistory();if(!silent)setNotice('Game saved successfully.','success');return true}catch(err){console.error(err);saveLocalHistory();els.db.textContent=`DB: error`;if(!silent)setNotice(`Database save failed: ${err.message||err}. A local backup was saved.`,'error');return false}}
async function checkDB(){if(!supabaseClient){els.db.textContent='DB: local mode';return false}try{const {error}=await supabaseClient.from('games').select('id').limit(1);if(error)throw error;els.db.textContent='DB: connected';return true}catch(e){els.db.textContent='DB: offline';return false}}
async function loadGameFromDB(id){if(!supabaseClient){loadLocalGame(id);return}try{const {data:g,error:ge}=await supabaseClient.from('games').select('id,name,max_score,ended,created_at').eq('id',id).single();if(ge)throw ge;const {data:ms,error:me}=await supabaseClient.from('members').select('id,name,total,eliminated').eq('game_id',id).order('id',{ascending:true});if(me)throw me;const {data:rs,error:re}=await supabaseClient.from('rounds').select('round_number,scores').eq('game_id',id).order('round_number',{ascending:true});if(re)throw re;members=(ms||[]).map(normalizeMember);rounds=(rs||[]).map(r=>normalizeRound(r.scores));maxScore=Number(g.max_score)||0;ended=Boolean(g.ended);inGame=!ended;DB_GAME_ID=id;roundNumber=rounds.length+1;persist();render();setNotice('Saved game loaded successfully.','success')}catch(e){console.error(e);setNotice(`Load failed: ${e.message||e}`,'error')}}
function loadLocalGame(id){const g=localHistory().find(x=>x.id===id);if(!g)return;members=(g.members||[]).map(normalizeMember);rounds=(g.rounds||[]).map(r=>normalizeRound(r.scores));maxScore=Number(g.max_score)||0;ended=true;inGame=false;DB_GAME_ID=null;roundNumber=rounds.length+1;persist();render();setNotice('Local saved game loaded.','success')}
async function deleteGame(id){if(!id)return;try{if(supabaseClient){const {data:g,error:ge}=await supabaseClient.from('games').select('id').eq('id',id).maybeSingle();if(ge)throw ge;if(!g)throw new Error('Game not found');const {error:re}=await supabaseClient.from('rounds').delete().eq('game_id',id);if(re)throw re;const {error:me}=await supabaseClient.from('members').delete().eq('game_id',id);if(me)throw me;const {data:deleted,error:de}=await supabaseClient.from('games').delete().eq('id',id).select('id');if(de)throw de;if(!deleted?.length)throw new Error('No game was deleted. Check the games DELETE policy in Supabase.');if(DB_GAME_ID===id){DB_GAME_ID=null;persist()}}else{const h=localHistory().filter(x=>x.id!==id);localStorage.setItem(KEYS.history,JSON.stringify(h))}await showHistoryPage(currentHistoryPage);setNotice('Saved game deleted.','success')}catch(e){console.error(e);setNotice(`Delete failed: ${e.message||e}`,'error')}}
async function fetchHistory(page=1){if(!supabaseClient){const h=localHistory();historyTotalCount=h.length;return h.slice((page-1)*5,page*5).map(g=>({game:g,members:g.members||[],rounds:g.rounds||[],winner:{names:g.winner||[]}}))}const from=(page-1)*5,to=page*5-1;const {data,error,count}=await supabaseClient.from('games').select('id,name,max_score,ended,created_at',{count:'exact'}).order('created_at',{ascending:false}).range(from,to);if(error)throw error;historyTotalCount=count||0;return Promise.all((data||[]).map(async g=>{const {data:ms,error:me}=await supabaseClient.from('members').select('id,name,total,eliminated').eq('game_id',g.id).order('id',{ascending:true});if(me)throw me;const {data:rs,error:re}=await supabaseClient.from('rounds').select('round_number,scores').eq('game_id',g.id).order('round_number',{ascending:true});if(re)throw re;const pool=(ms||[]).filter(m=>!m.eliminated);const vals=pool.length?pool.map(m=>Number(m.total)||0):[];const min=vals.length?Math.min(...vals):null;return {game:g,members:ms||[],rounds:rs||[],winner:{names:min===null?[]:(ms||[]).filter(m=>Number(m.total)===min).map(m=>m.name),score:min}}}))}
function renderHistory(details){els.historyList.innerHTML='';if(!details.length){els.historyList.innerHTML='<div class="empty-state">No saved games found.</div>';return}details.forEach(d=>{const card=document.createElement('article');card.className='history-card';const title=document.createElement('div');title.className='history-title';title.textContent=`${d.game.name||d.game.id}${d.game.created_at?' · '+new Date(d.game.created_at).toLocaleString():''}`;const players=document.createElement('div');players.className='history-players';players.textContent=`Players: ${(d.members||[]).map(m=>`${m.name} (${m.total||0})`).join(', ')||'None'}`;card.append(title,players);if(d.rounds?.length){const wrap=document.createElement('div');wrap.className='history-rounds';const t=document.createElement('table');t.className='history-rounds-table';const hr=document.createElement('tr');['Round',...(d.members||[]).map(m=>m.name)].forEach(x=>{const th=document.createElement('th');th.textContent=x;hr.appendChild(th)});const thead=document.createElement('thead');thead.appendChild(hr);t.appendChild(thead);const tb=document.createElement('tbody');d.rounds.forEach((r,i)=>{const tr=document.createElement('tr');const td=document.createElement('td');td.textContent=`R${r.round_number||i+1}`;tr.appendChild(td);(d.members||[]).forEach((m,mi)=>{const x=document.createElement('td');x.textContent=r.scores?.[mi]??0;tr.appendChild(x)});tb.appendChild(tr)});t.appendChild(tb);wrap.appendChild(t);card.appendChild(wrap)}const win=document.createElement('div');win.className='history-winner';win.textContent=d.winner?.names?.length?`Winner: ${d.winner.names.join(', ')} (${d.winner.score})`:'Winner: -';card.appendChild(win);const actions=document.createElement('div');actions.className='history-card-actions';const load=document.createElement('button');load.textContent='Load';load.onclick=()=>showConfirm('Load this saved game? Current game state will be replaced.',async()=>{closeConfirm();await loadGameFromDB(d.game.id);els.historyModal.hidden=true});const del=document.createElement('button');del.className='btn-danger';del.textContent='Delete';del.onclick=()=>showConfirm('Delete this saved game permanently?',async()=>{closeConfirm();await deleteGame(d.game.id)});actions.append(load,del);card.appendChild(actions);els.historyList.appendChild(card)})}
async function showHistoryPage(page=1){els.historyList.innerHTML='<div class="loading">Loading history...</div>';try{const details=await fetchHistory(page);const totalPages=Math.max(1,Math.ceil(historyTotalCount/5));currentHistoryPage=Math.min(Math.max(1,page),totalPages);els.pageInfo.textContent=`Page ${currentHistoryPage} / ${totalPages}`;els.prev.disabled=currentHistoryPage<=1;els.next.disabled=currentHistoryPage>=totalPages;renderHistory(details)}catch(e){els.historyList.textContent=`Failed to load history: ${e.message||e}`;els.prev.disabled=true;els.next.disabled=true}}
async function openHistory(){els.historyModal.hidden=false;currentHistoryPage=1;await checkDB();await showHistoryPage(1)}
els.addForm.addEventListener('submit',e=>{e.preventDefault();addMember(els.nameInput.value)});els.createSlots.addEventListener('click',createSlots);els.cancelSlots.addEventListener('click',cancelSlots);els.bulkForm.addEventListener('submit',saveBulk);els.max.addEventListener('input',()=>{maxScore=Number(els.max.value)||0;localStorage.setItem(KEYS.max,String(maxScore));updateStartButton()});els.start.addEventListener('click',startGame);els.roundForm.addEventListener('submit',submitRound);els.undo.addEventListener('click',undoRound);els.endGameBtn.addEventListener('click',()=>endGame(true));els.resetBtn.addEventListener('click',resetGame);els.newGame.addEventListener('click',newGame);els.saveGameBtn.addEventListener('click',()=>saveGame(false));els.historyBtn.addEventListener('click',openHistory);els.historyClose.addEventListener('click',()=>els.historyModal.hidden=true);els.historyCloseTop.addEventListener('click',()=>els.historyModal.hidden=true);els.historyRefresh.addEventListener('click',()=>showHistoryPage(currentHistoryPage));els.prev.addEventListener('click',()=>showHistoryPage(currentHistoryPage-1));els.next.addEventListener('click',()=>showHistoryPage(currentHistoryPage+1));els.confirmNo.addEventListener('click',closeConfirm);els.confirmYes.addEventListener('click',async()=>{const fn=confirmAction;closeConfirm();if(fn)await fn()});els.confirmModal.addEventListener('click',e=>{if(e.target===els.confirmModal)closeConfirm()});els.historyModal.addEventListener('click',e=>{if(e.target===els.historyModal)els.historyModal.hidden=true});window.addEventListener('beforeunload',persist);
els.authForm.addEventListener('submit',authenticate);els.authToggle.addEventListener('click',()=>{authRegisterMode=!authRegisterMode;els.authForm.reset();setAuthNotice('');updateAuthMode()});els.signOut.addEventListener('click',signOut);updateAuthMode();
if(supabaseClient){supabaseClient.auth.onAuthStateChange((_event,session)=>handleAuthSession(session));supabaseClient.auth.getSession().then(({data})=>handleAuthSession(data.session))}else{handleAuthSession(null);checkDB()}
